version: 3
files:
  - pattern: .github/workflows/*.yml
  - pattern: .github/workflows/*.yaml
  - pattern: template/.github/workflows/*.yml
  - pattern: template/.github/workflows/*.yaml
  - pattern: template/.github/actions/*/action.yml
  - pattern: template/.github/actions/*/action.yaml
